import type { TypedDocsConfig } from '../TypedDocsConfig'

const TIPOS = [
  { value: 'transferencia', label: 'Transferencia' },
  { value: 'recibo_domiciliado', label: 'Recibo domiciliado' },
  { value: 'adeudo_sepa', label: 'Adeudo SEPA' },
  { value: 'pagare', label: 'Pagaré' },
  { value: 'cheque', label: 'Cheque' },
  { value: 'efectivo', label: 'Efectivo' },
  { value: 'tarjeta', label: 'Tarjeta' },
  { value: 'bizum', label: 'Bizum' },
  { value: 'ingreso_caja', label: 'Ingreso en caja' },
  { value: 'aeat_nrc', label: 'AEAT NRC' },
  { value: 'otro', label: 'Otro' },
]

export const JUSTIFICANTES_PAGO_CONFIG: TypedDocsConfig = {
  table: 'justificantes_pago',
  title: 'Justificantes de pago',
  subtitle: 'Transferencias, recibos, adeudos SEPA, NRC AEAT, etc. Conciliación contra facturas/nóminas/modelos.',
  icon: '💸',
  newLabel: 'Justificante',
  columns: [
    { key: 'tipo_justificante', label: 'Tipo', type: 'select', options: TIPOS, required: true },
    { key: 'fecha_operacion', label: 'Fecha operación', type: 'date', required: true },
    { key: 'fecha_valor', label: 'Fecha valor', type: 'date', hideInList: true },
    { key: 'beneficiario_nombre', label: 'Beneficiario', type: 'text' },
    { key: 'beneficiario_nif', label: 'NIF beneficiario', type: 'text', hideInList: true },
    { key: 'ordenante_nombre', label: 'Ordenante', type: 'text', hideInList: true },
    { key: 'ordenante_nif', label: 'NIF ordenante', type: 'text', hideInList: true },
    { key: 'banco_emisor', label: 'Banco', type: 'text', hideInList: true },
    { key: 'iban_ordenante', label: 'IBAN ordenante', type: 'text', hideInList: true },
    { key: 'iban_beneficiario', label: 'IBAN beneficiario', type: 'text', hideInList: true },
    { key: 'referencia_operacion', label: 'Referencia / NRC', type: 'text' },
    { key: 'concepto', label: 'Concepto', type: 'textarea' },
    { key: 'importe', label: 'Importe', type: 'numeric', required: true },
    { key: 'moneda', label: 'Moneda', type: 'text', hideInList: true },
    { key: 'comision', label: 'Comisión', type: 'numeric', hideInList: true },
    { key: 'conciliado', label: 'Conciliado', type: 'boolean' },
    { key: 'fecha_conciliacion', label: 'Fecha conciliación', type: 'date', hideInList: true },
    { key: 'documento_referenciado_texto', label: 'Referencia textual', type: 'text', hideInList: true },
    { key: 'invoice_id', label: 'Factura (ID)', type: 'text', hideInList: true },
    { key: 'contrato_id', label: 'Contrato (ID)', type: 'text', hideInList: true },
    { key: 'payroll_id', label: 'Nómina (ID)', type: 'text', hideInList: true },
    { key: 'seguro_id', label: 'Seguro (ID)', type: 'text', hideInList: true },
    { key: 'modelo_fiscal_id', label: 'Modelo fiscal (ID)', type: 'text', hideInList: true },
  ],
  filters: [
    { key: 'tipo_justificante', label: 'Tipo', type: 'select', options: TIPOS },
    { key: 'conciliado', label: 'Conciliado', type: 'boolean' },
    { key: 'fecha_operacion', label: 'Fecha operación', type: 'date_range' },
    { key: 'importe', label: 'Importe (€)', type: 'numeric_range' },
    { key: 'beneficiario_nombre', label: 'Beneficiario', type: 'text' },
  ],
  defaultSort: { column: 'fecha_operacion', order: 'desc' },
  kpis: [
    { label: 'Total justificantes', compute: 'count' },
    { label: 'Conciliados', compute: 'count_filter', filter: { key: 'conciliado', value: true }, accent: 'green' },
    { label: 'Sin conciliar', compute: 'count_filter', filter: { key: 'conciliado', value: false }, accent: 'amber' },
    { label: 'Importe total', compute: 'sum', field: 'importe', isMoney: true },
  ],
  emptyMessage: 'Sin justificantes de pago.',
}
