import type { TypedDocsConfig } from '../TypedDocsConfig'

const TIPOS_FINCA = [
  { value: 'urbana', label: 'Urbana' },
  { value: 'rustica', label: 'Rústica' },
  { value: 'solar', label: 'Solar' },
  { value: 'edificio', label: 'Edificio' },
  { value: 'vivienda', label: 'Vivienda' },
  { value: 'local', label: 'Local' },
  { value: 'garaje', label: 'Garaje' },
  { value: 'trastero', label: 'Trastero' },
  { value: 'oficina', label: 'Oficina' },
  { value: 'nave_industrial', label: 'Nave industrial' },
  { value: 'otro', label: 'Otro' },
]

export const NOTAS_SIMPLES_CONFIG: TypedDocsConfig = {
  table: 'notas_simples',
  title: 'Notas simples',
  subtitle: 'Notas simples del Registro de la Propiedad. Vínculo con properties por finca registral / referencia catastral.',
  icon: '🏠',
  newLabel: 'Nota simple',
  columns: [
    { key: 'registro_propiedad', label: 'Registro', type: 'text', placeholder: 'Ej: Madrid nº 30' },
    { key: 'numero_finca', label: 'Nº finca', type: 'text' },
    { key: 'idufir', label: 'IDUFIR', type: 'text', hideInList: true },
    { key: 'referencia_catastral', label: 'Ref. catastral', type: 'text' },
    { key: 'tomo', label: 'Tomo', type: 'text', hideInList: true },
    { key: 'libro', label: 'Libro', type: 'text', hideInList: true },
    { key: 'folio', label: 'Folio', type: 'text', hideInList: true },
    { key: 'tipo_finca', label: 'Tipo finca', type: 'select', options: TIPOS_FINCA },
    { key: 'descripcion_finca', label: 'Descripción', type: 'textarea' },
    { key: 'superficie_construida_m2', label: 'Sup. construida (m²)', type: 'numeric', hideInList: true },
    { key: 'superficie_util_m2', label: 'Sup. útil (m²)', type: 'numeric', hideInList: true },
    { key: 'superficie_parcela_m2', label: 'Sup. parcela (m²)', type: 'numeric', hideInList: true },
    { key: 'cuota_participacion', label: 'Cuota participación', type: 'numeric', hideInList: true },
    { key: 'direccion_completa', label: 'Dirección', type: 'text' },
    { key: 'codigo_postal', label: 'CP', type: 'text', hideInList: true },
    { key: 'municipio', label: 'Municipio', type: 'text', hideInList: true },
    { key: 'provincia', label: 'Provincia', type: 'text', hideInList: true },
    { key: 'fecha_expedicion', label: 'Fecha expedición', type: 'date' },
    { key: 'fecha_vigencia', label: 'Fecha vigencia', type: 'date', hideInList: true },
    { key: 'registrador', label: 'Registrador', type: 'text', hideInList: true },
    { key: 'cuotas_pendientes_registro', label: 'Cuotas pendientes', type: 'numeric', hideInList: true },
    { key: 'property_id', label: 'Inmueble (ID)', type: 'text', hideInList: true },
  ],
  filters: [
    { key: 'tipo_finca', label: 'Tipo finca', type: 'select', options: TIPOS_FINCA },
    { key: 'registro_propiedad', label: 'Registro', type: 'text' },
    { key: 'fecha_expedicion', label: 'Fecha expedición', type: 'date_range' },
    { key: 'provincia', label: 'Provincia', type: 'text' },
    { key: 'municipio', label: 'Municipio', type: 'text' },
  ],
  defaultSort: { column: 'fecha_expedicion', order: 'desc' },
  kpis: [
    { label: 'Total notas', compute: 'count' },
    { label: 'Viviendas', compute: 'count_filter', filter: { key: 'tipo_finca', value: 'vivienda' } },
    { label: 'Locales', compute: 'count_filter', filter: { key: 'tipo_finca', value: 'local' } },
    { label: 'Solares', compute: 'count_filter', filter: { key: 'tipo_finca', value: 'solar' } },
  ],
  emptyMessage: 'Sin notas simples.',
}
