import type { TypedDocsConfig } from '../TypedDocsConfig'

const TIPOS_SEGURO = [
  { value: 'decenal_loe', label: 'Decenal LOE' },
  { value: 'todo_riesgo_construccion', label: 'Todo riesgo construcción' },
  { value: 'rc_general', label: 'RC general' },
  { value: 'rc_profesional', label: 'RC profesional' },
  { value: 'multirriesgo_hogar', label: 'Multirriesgo hogar' },
  { value: 'multirriesgo_comercio', label: 'Multirriesgo comercio' },
  { value: 'multirriesgo_industrial', label: 'Multirriesgo industrial' },
  { value: 'comunidades', label: 'Comunidades' },
  { value: 'vida', label: 'Vida' },
  { value: 'salud', label: 'Salud' },
  { value: 'accidentes', label: 'Accidentes' },
  { value: 'automovil', label: 'Automóvil' },
  { value: 'flota', label: 'Flota' },
  { value: 'transporte', label: 'Transporte' },
  { value: 'credito', label: 'Crédito' },
  { value: 'caucion', label: 'Caución' },
  { value: 'impago_alquileres', label: 'Impago alquileres' },
  { value: 'otro', label: 'Otro' },
]

const ESTADOS = [
  { value: 'vigente', label: 'Vigente' },
  { value: 'suspendida', label: 'Suspendida' },
  { value: 'vencida', label: 'Vencida' },
  { value: 'anulada', label: 'Anulada' },
  { value: 'siniestro_abierto', label: 'Siniestro abierto' },
]

export const SEGUROS_CONFIG: TypedDocsConfig = {
  table: 'seguros',
  title: 'Seguros',
  subtitle: 'Pólizas del grupo (decenal LOE, RC, multirriesgo, automóvil, etc).',
  icon: '🛡️',
  newLabel: 'Póliza',
  columns: [
    { key: 'numero_poliza', label: 'Nº póliza', type: 'text', required: true },
    { key: 'aseguradora', label: 'Aseguradora', type: 'text' },
    { key: 'aseguradora_nif', label: 'NIF aseguradora', type: 'text', hideInList: true },
    { key: 'mediador_corredor', label: 'Mediador / corredor', type: 'text', hideInList: true },
    { key: 'mediador_nif', label: 'NIF mediador', type: 'text', hideInList: true },
    { key: 'tipo_seguro', label: 'Tipo', type: 'select', options: TIPOS_SEGURO, required: true },
    { key: 'fecha_emision', label: 'Emisión', type: 'date', hideInList: true },
    { key: 'fecha_efecto', label: 'Efecto', type: 'date' },
    { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date' },
    { key: 'prorroga_automatica', label: 'Prórroga automática', type: 'boolean', hideInList: true },
    { key: 'prima_neta', label: 'Prima neta', type: 'numeric', hideInList: true },
    { key: 'recargos', label: 'Recargos', type: 'numeric', hideInList: true },
    { key: 'impuestos', label: 'Impuestos', type: 'numeric', hideInList: true },
    { key: 'prima_total', label: 'Prima total', type: 'numeric' },
    { key: 'forma_pago', label: 'Forma pago', type: 'text', hideInList: true },
    { key: 'capital_asegurado', label: 'Capital asegurado', type: 'numeric', hideInList: true },
    { key: 'franquicia', label: 'Franquicia', type: 'numeric', hideInList: true },
    { key: 'estado', label: 'Estado', type: 'badge', options: ESTADOS, required: true },
    { key: 'property_id', label: 'Inmueble (ID)', type: 'text', hideInList: true },
    { key: 'project_id', label: 'Proyecto (ID)', type: 'text', hideInList: true },
  ],
  filters: [
    { key: 'tipo_seguro', label: 'Tipo', type: 'select', options: TIPOS_SEGURO },
    { key: 'estado', label: 'Estado', type: 'select', options: ESTADOS },
    { key: 'aseguradora', label: 'Aseguradora', type: 'text' },
    { key: 'fecha_vencimiento', label: 'Vencimiento', type: 'date_range' },
  ],
  defaultSort: { column: 'fecha_vencimiento', order: 'asc' },
  kpis: [
    { label: 'Total pólizas', compute: 'count' },
    { label: 'Vigentes', compute: 'count_filter', filter: { key: 'estado', value: 'vigente' }, accent: 'green' },
    { label: 'Prima total acumulada', compute: 'sum', field: 'prima_total', isMoney: true },
    { label: 'Siniestros abiertos', compute: 'count_filter', filter: { key: 'estado', value: 'siniestro_abierto' }, accent: 'red' },
  ],
  emptyMessage: 'Sin pólizas registradas.',
}
